# Utiliser une image Python
FROM python:3.10-slim

# Définir le dossier de travail dans le conteneur
WORKDIR /app

# Copier les fichiers de dépendances
COPY requirements.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copier tout le code de l’application
COPY . .

# Exposer le port utilisé par Flask
EXPOSE 5000

# Commande de lancement
CMD ["python", "main.py"]
